apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - nodePort: 31090
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promdeploy
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: sarthaksharma5/prometheus
        imagePullPolicy: IfNotPresent
        name: promcont
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /etc/prometheus/data
          name: prometheus-vol
      volumes:
      - name: prometheus-vol
        persistentVolumeClaim:
          claimName: prometheus-pvc